const Images = {
    main_bg: require('../../assets/images/background/main_bg.png'),
    main_bg2: require('../../assets/images/background/main_bg2.png'),
    main_bg3: require('../../assets/images/background/main_bg3.png'),
    sidemenu_bg: require('../../assets/images/background/sidemenu.png'),
    user_img: require('../../assets/images/background/user.png'),
    main_logo: require('../../assets/images/logo/main_logo.png'),
    black_logo: require('../../assets/images/logo/black_logo.png'),
    white_logo: require('../../assets/images/logo/white_logo.png'),
    checkbox_selected: require('../../assets/images/checkbox/checked.png'),
    checkbox_normal: require('../../assets/images/checkbox/unchecked.png'),
    back_dark: require('../../assets/images/button/back_dark.png'),
    back_white: require('../../assets/images/button/back_white.png'),
    close_white: require('../../assets/images/button/close_white.png'),
    close_dark: require('../../assets/images/button/close_dark.png'),
    facebook_icon: require('../../assets/images/icons/facebook.png'),
    google_icon: require('../../assets/images/icons/google.png'),
    apple_icon: require('../../assets/images/icons/apple.png'),
    plus_icon: require('../../assets/images/icons/plus.png'),
    minus_icon: require('../../assets/images/icons/minus.png'),
    search_icon: require('../../assets/images/icons/search.png'),
    search_dark_icon: require('../../assets/images/icons/search_dark.png'),
    favouriteHeader_icon: require('../../assets/images/icons/favourite.png'),
    phone_icon: require('../../assets/images/icons/phone.png'),
    web_icon: require('../../assets/images/icons/web.png'),
    email_icon: require('../../assets/images/icons/email.png'),
    menu_icon: require('../../assets/images/icons/menu.png'),
    notification_icon: require('../../assets/images/icons/notification.png'),
    trending_icon: require('../../assets/images/icons/trending.png'),
    footer_logo: require('../../assets/images/logo/footer_logo.png'),
    sideAbout_icon: require('../../assets/images/icons/sidemenu/about.png'),
    sideContact_icon: require('../../assets/images/icons/sidemenu/contact.png'),
    sideFAQ_icon: require('../../assets/images/icons/sidemenu/FAQ.png'),
    sideLogout_icon: require('../../assets/images/icons/sidemenu/logout.png'),
    sideLoyalty_icon: require('../../assets/images/icons/sidemenu/loyalty.png'),
    sideOffer_icon: require('../../assets/images/icons/sidemenu/offer.png'),
    sideSetting_icon: require('../../assets/images/icons/sidemenu/setting.png'),
    sideSurvey_icon: require('../../assets/images/icons/sidemenu/survey.png'),
    sideSupport_icon: require('../../assets/images/icons/sidemenu/support.png'),
    chef_icon: require('../../assets/images/icons/chef.png'),
    add_shopping: require('../../assets/images/icons/add_shopping.png'),
    add_shopping_dark: require('../../assets/images/icons/add_shopping_dark.png'),
    pay_icon: require('../../assets/images/icons/pay.png'),
    more_icon: require('../../assets/images/icons/more.png'),
    edit_icon: require('../../assets/images/icons/edit.png'),
    password_icon: require('../../assets/images/icons/password.png'),
    visa_icon: require('../../assets/images/icons/visa.png'),
    filter_dark_icon: require('../../assets/images/icons/filter.png'),
    delete_dark_icon: require('../../assets/images/icons/delete_dark.png'),
    none_approve_icon: require('../../assets/images/icons/none_approve.png'),
    approve_icon: require('../../assets/images/icons/approve.png'),
    import_dark_icon: require('../../assets/images/icons/import_dark.png'),
    scan_dark_icon: require('../../assets/images/icons/scan_dark.png'),

    home_icon: require('../../assets/images/icons/bottombar/home.png'),
    home_selected_icon: require('../../assets/images/icons/bottombar/home_selected.png'),
    shopping_icon: require('../../assets/images/icons/bottombar/shopping.png'),
    shopping_selected_icon: require('../../assets/images/icons/bottombar/shopping_selected.png'),
    favourite_icon: require('../../assets/images/icons/bottombar/favourite.png'),
    favourite_selected_icon: require('../../assets/images/icons/bottombar/favourite_selected.png'),
    profile_icon: require('../../assets/images/icons/bottombar/profile.png'),
    profile_selected_icon: require('../../assets/images/icons/bottombar/profile_selected.png'),
    camera_icon: require('../../assets/images/icons/bottombar/camera.png'),
    favourite_white_icon: require('../../assets/images/icons/favourite_white.png'),
    favourite_dark_icon: require('../../assets/images/icons/favourite_dark.png'),
    date_icon: require('../../assets/images/icons/date.png'),
    location_icon: require('../../assets/images/icons/location.png'),
    eat_icon: require('../../assets/images/icons/recipe/eat.png'),
    pot_icon: require('../../assets/images/icons/recipe/pot.png'),
    time_icon: require('../../assets/images/icons/recipe/time.png'),
    play_icon: require('../../assets/images/icons/play.png'),
    wallet_icon: require('../../assets/images/icons/profile/wallet.png'),
    family_icon: require('../../assets/images/icons/profile/family.png'),
    receipts_icon: require('../../assets/images/icons/profile/receipts.png'),

    product1: require('../../assets/images/product/product1.png'),
    recipe1: require('../../assets/images/recipes/recipe1.png'),
    item1: require('../../assets/images/product/items/item1.png'),
    treding: require('../../assets/images/product/trending.png'),
    recipe_img: require('../../assets/images/product/recipe.png'),
    loyalty_img: require('../../assets/images/product/loyalty.png'),
    loyalty_detail_img: require('../../assets/images/product/loyalty/loyalty_detail.png'),
    survey_img: require('../../assets/images/product/survey.png'),
    programs1_img: require('../../assets/images/product/loyalty/programs/programs1.png'),
    programs2_img: require('../../assets/images/product/loyalty/programs/programs2.png'),
    programs3_img: require('../../assets/images/product/loyalty/programs/programs3.png'),
    programs4_img: require('../../assets/images/product/loyalty/programs/programs4.png'),
    events1_img: require('../../assets/images/product/loyalty/events/events1.png'),
    user1_img: require('../../assets/images/product/loyalty/people/user1.png'),

    //categories no needed
    // beverages_category: require('../../assets/images/product/categories/beverages.png'),
    // cannedFood_category: require('../../assets/images/product/categories/canned_food.png'),
 
    // Berverages
        //categories/beverages/softdrinks
        softdrinks_img1: require('../../assets/images/product/categories/beverages/soft_drinks/soft_drinks1.png'),
        //categories/beverages/alcohol
        alcohol_img1: require('../../assets/images/product/categories/beverages/alcohol/alcohol1.png'),
    // Berverages end

    // Canned Food
        // categories/canned food/vegetable_fruits
        vegetableFruits_img1: require('../../assets/images/product/categories/canned_food/vegetable_fruits/vegetable_fruits1.png'),
    // Canned Food end
}

export default Images;